### ISSUE TITLE
Push right 

### ISSUE THREAD

**Issue by SightlessDog** [nathalieclaire/planet-pals#55]
Please can you give the right to push to the repo

**Comment by SightlessDog** [comment]
I don't mind that and that's what I want to do but I cannot push at all :)

**Comment by abductedRhino** [comment]
Right, I'll have to check on my laptop. I will update this when it is done:)

**Comment by nathalieclaire** [comment]
We have checked our repository settings. There are no restrictions set under settings/moderation-options, so you should be able to fork the repo and send a pull request. Thats what abductedrhino and estella are doing right now. What do you want to change? :)

**Comment by SightlessDog** [comment]
Actually I didn't want to fork it, but it is okay it is about the README.md file, it would be nice if it has more like a description of your project, how to install how to start, and if you have dockerized the project you could also mention that but otherwise the rest looks good 👍
